# <b><span style='color:#0B2F9F'>Pengantar</span></b>

Dalam pengelolaan data, kemampuan untuk menampilkan informasi dengan format yang tepat serta menggali data secara mendalam menjadi hal yang sangat penting. Format angka dan tanggal membantu memastikan data tersaji secara konsisten, mudah dibaca, dan sesuai konteks, sehingga hasil analisis lebih akurat dan informatif. Sementara itu, penggunaan subquery memungkinkan pengambilan data secara lebih fleksibel dan efisien, dengan cara memecah proses pencarian menjadi langkah-langkah yang lebih terarah. Dengan memahami kedua konsep ini, seseorang dapat mengolah data dengan lebih rapi, melakukan analisis yang lebih mendalam, serta menghasilkan informasi yang lebih bermakna dan dapat diandalkan.

# <b><span style='color:#0B2F9F'>Set up</span></b>

Dibutuhkan proses autentikasi dari Google Colab ke Google Big Query. Ikuti langkah berikut https://drive.google.com/file/d/1gW8alZ_PrvcrsieqWCHOR4ssLI_25BRc/view untuk detail step-by-step nya

In [ ]:
# Import library yang dibutuhkan
from google.colab import auth, data_table
from google.cloud import bigquery
from pandas_gbq import to_gbq

# Proses autentikasi akun
auth.authenticate_user()
print('Authenticated')

Authenticated

In [ ]:
# Buat BigQuery client
project_id = 'dqlab-putri512'
client = bigquery.Client(project = project_id)

In [ ]:
# Buat BigQuery client
project_id = 'dqlab-putri512' # isikan project_id disini
client = bigquery.Client(project = project_id)

Sebagai Data Engineer, Antara (Jr. Data Engineer di DQPizza) ditugaskan untuk membuat data mart untuk kebutuhan detail transaksi. Dengan memanfaatkan relasi antar table, Antara mengeksekusi suatu perintah  untuk membuat table f_detail_transaksi (sebuah tabel fact yang berisi data transaksi secara rinci, mencakup ukuran-ukuran kuantitatif seperti jumlah, harga, total nilai transaksi, dan lain sebagainya) hingga terbentuklah tabel f_detail_transaksi.

<br>
<code>SELECT * FROM dqlab-9876543.dq_pizza.f_detail_transaksi</code>
<br><br>
<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/SQL%20-%20f_detail_transaksi.png" width="30%">

Data dibawah (f_detail_transaksi) akan digunakan pada modul ini

In [ ]:
%%bigquery --project {project_id} --verbose

SELECT
  *
FROM `dqlab-9876543.dq_pizza.f_detail_transaksi`

Executing query with job ID: 20008f13-e370-43d3-b56c-deeed0d59eb5
Query executing: 0.46s
Job ID 20008f13-e370-43d3-b56c-deeed0d59eb5 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,order_id,order_details_id,customer_id,order_maker_id,pizza_name,category,size,price,production_cost,quantity,order_date,order_time,completion_time,is_complain,complain_detail
0,TRX019321,TRXD043959,CUST003319,EMP000208,THE PEPPERONI PIZZA,CLASSIC,S,78975.0,62937.0,1,2024-11-26,13:58:49,14:26:52,0,None
1,TRX000734,TRXD001645,CUST003549,EMP000208,THE PEPPERONI PIZZA,CLASSIC,S,78975.0,62937.0,1,2024-01-12,20:00:30,20:27:49,0,None
2,TRX004103,TRXD009366,CUST006714,EMP000208,THE PEPPERONI PIZZA,CLASSIC,S,78975.0,62937.0,1,2024-03-10,19:10:04,19:39:33,0,None
3,TRX013010,TRXD029448,CUST005604,EMP000208,THE PEPPERONI PIZZA,CLASSIC,S,78975.0,62937.0,1,2024-08-05,18:06:43,18:32:51,0,None
4,TRX008857,TRXD020142,CUST004778,EMP000208,THE PEPPERONI PIZZA,CLASSIC,S,78975.0,62937.0,1,2024-05-29,13:21:21,13:45:23,0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48614,TRX003266,TRXD007413,CUST007085,EMP000756,THE BRIE CARRE PIZZA,supreme,S,191565.0,170505.0,1,2024-02-24,18:40:58,19:01:17,0,None
48615,TRX008441,TRXD019204,CUST007254,EMP000756,THE BRIE CARRE PIZZA,supreme,S,191565.0,170505.0,1,2024-05-21,21:14:52,21:30:47,0,None
48616,TRX001581,TRXD003564,CUST009381,EMP000756,THE GREEK PIZZA,CLASSIC,XXL,291195.0,260738.0,1,2024-01-27,16:28:38,16:54:32,0,None
48617,TRX016753,TRXD037944,CUST004945,EMP000756,THE GREEK PIZZA,CLASSIC,XXL,291195.0,260738.0,1,2024-10-10,17:54:55,18:06:01,0,None
48618,TRX002813,TRXD006366,CUST006714,EMP000756,THE GREEK PIZZA,CLASSIC,XXL,291195.0,260738.0,1,2024-02-16,18:15:02,18:29:26,0,None

# <b>A. <span style='color:#0B2F9F'><code>Data Type</code></span></b>

Data type dalam BigQuery adalah cara untuk mendefinisikan jenis data yang akan disimpan dalam tabel. Setiap kolom dalam tabel memiliki tipe data tertentu, yang menentukan apa yang dapat disimpan di kolom tersebut dan bagaimana data tersebut dapat diproses. Memahami tipe data ini penting untuk desain skema yang efisien dan untuk memastikan bahwa kueri dapat dijalankan dengan optimal.

<br>
<img src="https://hackolade.com/help/lib/BigQuery%20data%20types%20table.png" width="40%">

docs : <i><a href="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types">https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types</a></i>

# <b>B. <span style='color:#0B2F9F'><code>Operasi Tipe Data Numerik</code></span></b>

Dalam SQL, tipe data numerik digunakan untuk menyimpan nilai angka dan dapat dikelompokkan menjadi beberapa jenis sesuai peruntukannya (INT, FLOAT, NUMERIC, dll). Selain itu pada tipe data Numerik juga dapat dilakukan operasi matematis diantaranya :
<ol>
    <li>Operasi Aritmatika</li>
    <li>Fungsi Matematis</li>
    <li>Agregasi</li>
</ol>

## <b>B.1. <span style='color:#0B2F9F'><code>Operasi Aritmatika</code></span></b>
SQL mendukung operasi dasar aritmatika seperti penjumlahan, pengurangan, perkalian, pembagian dan modulo.

<img src="https://mazamanbd.wordpress.com/wp-content/uploads/2014/09/dd.jpg"><br><br>

Untuk dapat menerapkannya pada sebuah tabel gunakan contoh format berikut

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/refs/heads/main/Image/Materi-SQL/SQL%20-%20OperasiAritmatika.png" width="50%">

<i>docs : <a href="https://cloud.google.com/bigquery/docs/reference/standard-sql/operators">https://cloud.google.com/bigquery/docs/reference/standard-sql/operators</a></i>

#### <i><b><span style='color:#55679C'>Quest</span> : Pada tabel f_detail_transaksi, tampilkan semua kolom dan tambahkan satu kolom 'total_price' yang merupakan hasil perkalian antara harga dengan kuantitas (terbeli)! Urutkan berdasarkan kuantitas paling besar hingga ke terkecil </b></i>

In [ ]:
%%bigquery --project {project_id} --verbose

SELECT
  *,
  (price * quantity) AS total_price
FROM `dqlab-9876543.dq_pizza.f_detail_transaksi`
ORDER BY quantity DESC

Executing query with job ID: d4338ff9-73e5-49b9-8070-d34eb251312a
Query executing: 0.38s
Job ID d4338ff9-73e5-49b9-8070-d34eb251312a successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,order_id,order_details_id,customer_id,order_maker_id,pizza_name,category,size,price,production_cost,quantity,order_date,order_time,completion_time,is_complain,complain_detail,total_price
0,TRX005264,TRXD011977,CUST004837,EMP000286,THE BIG MEAT PIZZA,Classic,S,97200.0,81567.0,4,2024-03-30,13:24:35,13:35:43,0,None,388800.0
1,TRX008286,TRXD018876,CUST004105,EMP000437,THE BIG MEAT PIZZA,Classic,S,97200.0,81567.0,4,2024-05-19,12:42:46,13:11:40,0,None,388800.0
2,TRX015674,TRXD035497,CUST006814,EMP000302,THE CALIFORNIA CHICKEN PIZZA,CHICKEN,L,168075.0,118989.0,4,2024-09-19,14:16:35,14:40:53,0,None,672300.0
3,TRX018845,TRXD042847,CUST007150,EMP000756,THE BARBECUE CHICKEN PIZZA,CHICKEN,M,135675.0,99468.0,3,2024-11-18,12:25:12,12:50:38,0,None,407025.0
4,TRX000394,TRXD000903,CUST006034,EMP000231,THE PEPPERONI PIZZA,CLASSIC,M,101250.0,74682.0,3,2024-01-07,14:02:18,14:31:55,0,None,303750.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48614,TRX003266,TRXD007413,CUST007085,EMP000756,THE BRIE CARRE PIZZA,supreme,S,191565.0,170505.0,1,2024-02-24,18:40:58,19:01:17,0,None,191565.0
48615,TRX008441,TRXD019204,CUST007254,EMP000756,THE BRIE CARRE PIZZA,supreme,S,191565.0,170505.0,1,2024-05-21,21:14:52,21:30:47,0,None,191565.0
48616,TRX001581,TRXD003564,CUST009381,EMP000756,THE GREEK PIZZA,CLASSIC,XXL,291195.0,260738.0,1,2024-01-27,16:28:38,16:54:32,0,None,291195.0
48617,TRX016753,TRXD037944,CUST004945,EMP000756,THE GREEK PIZZA,CLASSIC,XXL,291195.0,260738.0,1,2024-10-10,17:54:55,18:06:01,0,None,291195.0
48618,TRX006145,TRXD014013,CUST008674,EMP000437,THE MEDITERRANEAN PIZZA,VEGGIE,S,97200.0,74844.0,1,2024-04-13,19:46:25,20:01:36,0,None,97200.0

#### <i><b><span style='color:#55679C'>Quest</span> : Selain total price, tambahkan juga total profit yang didapat tiap transaksi! (Lanjutkan hasil query quest diatas) </b></i>

In [ ]:
%%bigquery --project {project_id} --verbose

SELECT
  *,
  (price * quantity) AS total_price,
  ((price - production_cost) * quantity) AS total_profit
FROM `dqlab-9876543.dq_pizza.f_detail_transaksi`
ORDER BY quantity DESC

Executing query with job ID: 0c71e52d-1040-43f8-9786-27b5596f4587
Query executing: 1.43s
Job ID 0c71e52d-1040-43f8-9786-27b5596f4587 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,order_id,order_details_id,customer_id,order_maker_id,pizza_name,category,size,price,production_cost,quantity,order_date,order_time,completion_time,is_complain,complain_detail,total_price,total_profit
0,TRX005264,TRXD011977,CUST004837,EMP000286,THE BIG MEAT PIZZA,Classic,S,97200.0,81567.0,4,2024-03-30,13:24:35,13:35:43,0,None,388800.0,62532.0
1,TRX008286,TRXD018876,CUST004105,EMP000437,THE BIG MEAT PIZZA,Classic,S,97200.0,81567.0,4,2024-05-19,12:42:46,13:11:40,0,None,388800.0,62532.0
2,TRX015674,TRXD035497,CUST006814,EMP000302,THE CALIFORNIA CHICKEN PIZZA,CHICKEN,L,168075.0,118989.0,4,2024-09-19,14:16:35,14:40:53,0,None,672300.0,196344.0
3,TRX018845,TRXD042847,CUST007150,EMP000756,THE BARBECUE CHICKEN PIZZA,CHICKEN,M,135675.0,99468.0,3,2024-11-18,12:25:12,12:50:38,0,None,407025.0,108621.0
4,TRX000394,TRXD000903,CUST006034,EMP000231,THE PEPPERONI PIZZA,CLASSIC,M,101250.0,74682.0,3,2024-01-07,14:02:18,14:31:55,0,None,303750.0,79704.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48614,TRX003266,TRXD007413,CUST007085,EMP000756,THE BRIE CARRE PIZZA,supreme,S,191565.0,170505.0,1,2024-02-24,18:40:58,19:01:17,0,None,191565.0,21060.0
48615,TRX008441,TRXD019204,CUST007254,EMP000756,THE BRIE CARRE PIZZA,supreme,S,191565.0,170505.0,1,2024-05-21,21:14:52,21:30:47,0,None,191565.0,21060.0
48616,TRX001581,TRXD003564,CUST009381,EMP000756,THE GREEK PIZZA,CLASSIC,XXL,291195.0,260738.0,1,2024-01-27,16:28:38,16:54:32,0,None,291195.0,30457.0
48617,TRX016753,TRXD037944,CUST004945,EMP000756,THE GREEK PIZZA,CLASSIC,XXL,291195.0,260738.0,1,2024-10-10,17:54:55,18:06:01,0,None,291195.0,30457.0
48618,TRX006145,TRXD014013,CUST008674,EMP000437,THE MEDITERRANEAN PIZZA,VEGGIE,S,97200.0,74844.0,1,2024-04-13,19:46:25,20:01:36,0,None,97200.0,22356.0

#### <i><b><span style='color:#55679C'>Quest</span> : Bagaimana dengan customer paling loyal? Paling loyal diukur dari banyak profit restaurant yang dihasilkan. Tampilkan customer_id, total_frequency (berapa kali pembelian dalam setahun) dan total_profit yang diperoleh perusahaan, kelompokkan tiap customer_id! Urutkan berdasarkan customer_id dengan profit paling tinggi ke paling rendah! </b></i>

In [ ]:
%%bigquery --project {project_id} --verbose

SELECT
  customer_id,
  COUNT(DISTINCT order_id) AS total_frequency,
  SUM((price - production_cost) * quantity) AS total_profit
FROM `dqlab-9876543.dq_pizza.f_detail_transaksi`
GROUP BY customer_id
ORDER BY total_profit DESC

Executing query with job ID: 774ded34-5ca8-485a-8f41-1b2338b1be92
Query executing: 0.67s
Job ID 774ded34-5ca8-485a-8f41-1b2338b1be92 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

    customer_id  total_frequency  total_profit
0    CUST006333              741    47622169.0
1    CUST009381              702    44017426.0
2    CUST007656              614    37358334.0
3    CUST003549              580    36914292.0
4    CUST006964              521    32351562.0
..          ...              ...           ...
115  CUST008078               21     1070496.0
116  CUST005536               24      987714.0
117  CUST006892               12      858681.0
118  CUST003871               13      685908.0
119  CUST002478               17      659259.0

[120 rows x 3 columns]

## <b>B.2. <span style='color:#0B2F9F'><code>Fungsi Matematis</code></span></b>
SQL juga mendukung fungsi matematis dasar yang disajikan pada tabel berikut :

<table border="1">
    <thead>
        <tr>
            <th>Fungsi</th>
            <th>Deskripsi</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><code>ABS()</code></td>
            <td>Mengambil nilai absolut</td>
        </tr>
        <tr>
            <td><code>ROUND()</code></td>
            <td>Membulatkan angka</td>
        </tr>
        <tr>
            <td><code>CEIL()</code></td>
            <td>Membulatkan ke atas</td>
        </tr>
        <tr>
            <td><code>FLOOR()</code></td>
            <td>Membulatkan ke bawah</td>
        </tr>
        <tr>
            <td><code>POW()</code></td>
            <td>Menghitung pangkat</td>
        </tr>
    </tbody>
</table>

Untuk dapat menerapkannya pada sebuah tabel gunakan contoh format berikut

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/refs/heads/main/Image/Materi-SQL/SQL-FungsiMatematis.png" width="50%">

<i>docs : <a href="https://cloud.google.com/bigquery/docs/reference/standard-sql/mathematical_functions">https://cloud.google.com/bigquery/docs/reference/standard-sql/mathematical_functions</a></i>

#### <i><b><span style='color:#55679C'>Quest</span> : Sendja (Data Analyst di DQPizza) baru menyadari bahwa profit yang ia hitung pada quest sebelumnya merupakan profit sebelum pajak. Asumsikan pajak yang perlu dikeluarkan adalah 11% tiap kali transaksi. Hitung profit_before_tax, profit_after_tax dan tax_paid tiap order_id dan customer_id! Lakukan perhitungan untuk setiap transaksi yang valid (order_details_id tidak kosong)!</b></i>

Note : Bulatkan profit after tax sebanyak 2 angka dibelakang koma agar lebih rapi

In [ ]:
%%bigquery --project {project_id} --verbose

SELECT
  order_id,
  customer_id,
  ROUND(SUM((price - production_cost) * quantity),2) AS profit_before_tax,
  ROUND(SUM(((price - production_cost) * quantity) * (1-11/100)),2) AS profit_after_tax,
  ROUND(SUM(((price - production_cost) * quantity) * (11/100)),2) AS tax_paid
FROM `dqlab-9876543.dq_pizza.f_detail_transaksi`
WHERE order_details_id IS NOT NULL
GROUP BY order_id,customer_id
ORDER BY tax_paid DESC

Executing query with job ID: 79bbbfd8-eacd-4691-a885-5cd290d65159
Query executing: 2.25s
Job ID 79bbbfd8-eacd-4691-a885-5cd290d65159 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

        order_id customer_id  profit_before_tax  profit_after_tax  tax_paid
0      TRX018845  CUST007150           747954.0         665679.06  82274.94
1      TRX010760  CUST001704           684855.0         609520.95  75334.05
2      TRX004482  CUST003570           518481.0         461448.09  57032.91
3      TRX006169  CUST007656           494586.0         440181.54  54404.46
4      TRX009331  CUST004537           483813.0         430593.57  53219.43
...          ...         ...                ...               ...       ...
21341  TRX014887  CUST002604            10854.0           9660.06   1193.94
21342  TRX003839  CUST005127            10854.0           9660.06   1193.94
21343  TRX015013  CUST003570            10854.0           9660.06   1193.94
21344  TRX013817  CUST004547            10854.0           9660.06   1193.94
21345  TRX019167  CUST001704            10854.0           9660.06   1193.94

[21346 rows x 5 columns]

# <b>C. <span style='color:#0B2F9F'><code>Operasi Tipe Data Date</code></span></b>

Dalam SQL, tipe data date digunakan untuk menyimpan atau mengoperasikan data tanggal. Tipe data tanggal dapat dilakukan operasi berikut, diantaranya :
<ol>
    <li>Menampilkan Tanggal & Waktu saat ini</li>
    <li>Menambahkan atau Mengurangi Tanggal</li>
    <li>Mendapatkan Bagian Tanggal</li>
    <li>Menghitung Selisih Tanggal</li>
</ol>

<br><b>NOTE</b><br><br>
Hal-hal yang perlu diperhatikan dalam penggunaan operasi `date` adalah :
<ul>
    <li>Format tanggal standar SQL adalah 'YYYY-MM-DD' atau tahun - bulan - tanggal, contoh : 2024-10-14 menunjukan tanggal 14 October 2024</li>
    <li>Mengakses tanggal pada SQL perlu menggunakan tanda apit petik satu, contoh : '2024-10-14'</li>
    <li>Pastikan nilai atau kolom tanggal tipe datanya adalah DATE atau TIMESTAMP, jika tidak maka bisa dikonversi menjadi <code>DATE(tanggal)</code> atau <code>TIMESTAMP(tanggal)</code></li>
</ul>

<i>docs : <a href="https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions">https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions</a></i>

## <b>C.1. <span style='color:#0B2F9F'><code>Menampilkan Tanggal & Waktu Saat Ini</code></span></b>

Untuk menampilkan tanggal dan waktu saat ini dapat menggunakan fungsi berikut
<table border="1">
    <thead>
        <tr>
            <th>Fungsi</th>
            <th>Deskripsi</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><code>CURRENT_DATE()</code></td>
            <td>Mendapatkan Tanggal Hari ini Saja</td>
        </tr>
        <tr>
            <td><code>CURRENT_TIMESTAMP()</code></td>
            <td>Mendapatkan Tanggal & Waktu Hari ini (UTC)</td>
        </tr>
    </tbody>
</table>

UTC atau (Universal Time Coordinated) adalah waktu dasar yang tidak terpengaruh oleh zona waktu dan <i>daylight saving time</i>. UTC digunakan sebagai acuan untuk menghitung waktu di berbagai zona waktu di seluruh dunia (standar Greenwich Mean Time (London)). Selengkapnya baca <a href="https://internasional.kompas.com/read/2021/03/04/192042570/sejarah-penetapan-zona-waktu-di-dunia-hingga-usulan-penghapusannya?page=all">disini</a>.

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan semua kolom pada tabel f_detail_transaksi dan tambahkan kolom data_collection_time sebagai kolom metadata waktu pengambilan data</b></i><br>

In [ ]:
%%bigquery --project {project_id} --verbose

SELECT
  *,
  TIMESTAMP(DATETIME(CURRENT_TIMESTAMP(),"Asia/Jakarta")) AS data_collection_time
FROM `dqlab-9876543.dq_pizza.f_detail_transaksi`

Executing query with job ID: 47451012-6741-4742-a1b9-531c8f61a1a9
Query executing: 1.62s
Job ID 47451012-6741-4742-a1b9-531c8f61a1a9 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,order_id,order_details_id,customer_id,order_maker_id,pizza_name,category,size,price,production_cost,quantity,order_date,order_time,completion_time,is_complain,complain_detail,data_collection_time
0,TRX019321,TRXD043959,CUST003319,EMP000208,THE PEPPERONI PIZZA,CLASSIC,S,78975.0,62937.0,1,2024-11-26,13:58:49,14:26:52,0,None,2025-11-13 23:16:37.703147+00:00
1,TRX000734,TRXD001645,CUST003549,EMP000208,THE PEPPERONI PIZZA,CLASSIC,S,78975.0,62937.0,1,2024-01-12,20:00:30,20:27:49,0,None,2025-11-13 23:16:37.703147+00:00
2,TRX004103,TRXD009366,CUST006714,EMP000208,THE PEPPERONI PIZZA,CLASSIC,S,78975.0,62937.0,1,2024-03-10,19:10:04,19:39:33,0,None,2025-11-13 23:16:37.703147+00:00
3,TRX013010,TRXD029448,CUST005604,EMP000208,THE PEPPERONI PIZZA,CLASSIC,S,78975.0,62937.0,1,2024-08-05,18:06:43,18:32:51,0,None,2025-11-13 23:16:37.703147+00:00
4,TRX008857,TRXD020142,CUST004778,EMP000208,THE PEPPERONI PIZZA,CLASSIC,S,78975.0,62937.0,1,2024-05-29,13:21:21,13:45:23,0,None,2025-11-13 23:16:37.703147+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48614,TRX003266,TRXD007413,CUST007085,EMP000756,THE BRIE CARRE PIZZA,supreme,S,191565.0,170505.0,1,2024-02-24,18:40:58,19:01:17,0,None,2025-11-13 23:16:37.703147+00:00
48615,TRX008441,TRXD019204,CUST007254,EMP000756,THE BRIE CARRE PIZZA,supreme,S,191565.0,170505.0,1,2024-05-21,21:14:52,21:30:47,0,None,2025-11-13 23:16:37.703147+00:00
48616,TRX001581,TRXD003564,CUST009381,EMP000756,THE GREEK PIZZA,CLASSIC,XXL,291195.0,260738.0,1,2024-01-27,16:28:38,16:54:32,0,None,2025-11-13 23:16:37.703147+00:00
48617,TRX016753,TRXD037944,CUST004945,EMP000756,THE GREEK PIZZA,CLASSIC,XXL,291195.0,260738.0,1,2024-10-10,17:54:55,18:06:01,0,None,2025-11-13 23:16:37.703147+00:00
48618,TRX002813,TRXD006366,CUST006714,EMP000756,THE GREEK PIZZA,CLASSIC,XXL,291195.0,260738.0,1,2024-02-16,18:15:02,18:29:26,0,None,2025-11-13 23:16:37.703147+00:00

## <b>C.2. <span style='color:#0B2F9F'><code>Mengubah String menjadi Tanggal</code></span></b>

Adakalanya format tanggal yang disimpan pada database tidak disimpan dalam format date yang baku (<a href="https://www.iso.org/iso-8601-date-and-time-format.html">ISO 8601</a>) sehingga perlu penyesuaian. Gunakan : <br><br>
<table border="1">
    <thead>
        <tr>
            <th>Fungsi</th>
            <th>Deskripsi</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><code>PARSE_DATE(format, string_expression)</code></td>
            <td>Mengubah String menjadi Date</td>
        </tr>
        <tr>
            <td><code>FORMAT_DATE(format, date_expression)</code></td>
            <td>Mengubah Date menjadi String</td>
        </tr>
    </tbody>
</table><br>

Untuk detail format tanggal akses link berikut https://docs.cloud.google.com/bigquery/docs/reference/standard-sql/format-elements

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan order_date dan order_date_iso pada tabel f_detail_transaksi. Dimana kolom order_date merupakan kolom dengan data asli dan order_date_iso merupakan kolom order_date yang diubah formatnya menjadi YYYY-MM-DD sesuai ISO 8601!</b></i><br>

In [ ]:
%%bigquery --project {project_id} --verbose

SELECT
  order_date,
  FORMAT_DATE('%Y-%m-%d', order_date) AS order_date_iso
FROM `dqlab-9876543.dq_pizza.f_detail_transaksi`

Executing query with job ID: c53aaa53-f6e2-4097-9911-f21b2dca8af5
Query executing: 0.54s
Job ID c53aaa53-f6e2-4097-9911-f21b2dca8af5 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

       order_date order_date_iso
0      2024-01-12     2024-01-12
1      2024-03-10     2024-03-10
2      2024-08-05     2024-08-05
3      2024-05-29     2024-05-29
4      2024-07-10     2024-07-10
...           ...            ...
48614  2024-11-27     2024-11-27
48615  2024-11-27     2024-11-27
48616  2024-11-27     2024-11-27
48617  2024-11-27     2024-11-27
48618  2024-11-27     2024-11-27

[48619 rows x 2 columns]

## <b>C.3. <span style='color:#0B2F9F'><code>Menambahkan atau Mengurangi Tanggal</code></span></b>

<table border="1">
    <thead>
        <tr>
            <th>Fungsi</th>
            <th>Deskripsi</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><code>DATE_ADD(tanggal, INTERVAL jumlah_penambahan satuan_waktu)</code></td>
            <td>Menambahkan Tanggal pada Interval Tertentu</td>
        </tr>
        <tr>
            <td><code>DATE_SUB(tanggal, INTERVAL jumlah_penambahan satuan_waktu)</code></td>
            <td>Mengurangi Tanggal pada Interval Tertentu</td>
        </tr>
        <tr>
            <td><code>DATE_DIFF(end_date, start_date, date_part)</code></td>
            <td>Menghitung selisih tanggal</td>
        </tr>
    </tbody>
</table><br>

Sebagai contoh misalkan hari ini tanggal 30 Oktober 2025. Ingin diperoleh tanggal tepat 3 bulan yang lalu maka dapat digunakan sintaks `DATE_SUB(DATE('2025-10-30'), INTERVAL 3 MONTH)` maka akan diperoleh tanggal 30 Juli 2025.

#### <i><b><span style='color:#55679C'>Quest</span> : Manajer ingin melakukan analisa demografi customer, pada tabel customers tampilkan customer_id, customer_name, gender dan age-nya per hari ini!</b></i><br>

In [ ]:
%%bigquery --project {project_id} --verbose

SELECT
  customer_id,
  customer_name,
  gender,
  DATE_DIFF(CURRENT_DATE(), PARSE_DATE('%Y-%m-%d',birth_date), YEAR) AS age
FROM `dqlab-9876543.dq_pizza.customers`

Executing query with job ID: 07cddb77-8e6c-4ece-93b4-000ecc68c138
Query executing: 0.49s
Job ID 07cddb77-8e6c-4ece-93b4-000ecc68c138 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

    customer_id           customer_name gender  age
0    CUST007150     Salsabila Purnawati      F   35
1    CUST003319      Cornelia Wijayanti      F   28
2    CUST007254            Elma Maryati      F   41
3    CUST004392            Najwa Natsir      F   45
4    CUST005127           Hani Palastri      F   22
..          ...                     ...    ...  ...
132  CUST009056           Gada Winarsih      M   25
133  CUST009366        Mulyanto Suryono      M   24
134  CUST009522  Cakrawangsa Hutagalung      M   36
135  CUST009700       Asirwanda Hidayat      M   34
136  CUST009875            Wadi Jailani      M   29

[137 rows x 4 columns]

## <b>C.5. <span style='color:#0B2F9F'><code>Mendapatkan Bagian pada Tanggal</code></span></b>

Mengambil bagian tertentu dari tipe data tanggal, waktu, atau timestamp terkadang sangat perlu dilakukan untuk analisa data. Jika ingin didapatkan elemen tertentu, seperti tahun, bulan, hari, atau jam, dari nilai tanggal atau waktu gunakan fungsi berikut<br><br>

<code>EXTRACT(bagian FROM tanggal)</code>
<br><br>

Bagian yang bisa diambil pada tanggal diantaranya adalah
<table border="1">
    <thead>
        <tr>
            <th>Bagian</th>
            <th>Deskripsi</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><code>YEAR</code></td>
            <td>Mendapatkan Tahun pada Tanggal</td>
        </tr>
        <tr>
            <td><code>MONTH</code></td>
            <td>Mendapatkan Bulan pada Tanggal</td>
        </tr>
        <tr>
            <td><code>DAY</code></td>
            <td>Mendapatkan Hari (1-31) pada Tanggal</td>
        </tr>
        <tr>
            <td><code>WEEK</code></td>
            <td>Mendapatkan Minggu ke- pada Tanggal</td>
        </tr>
         <tr>
            <td><code>QUARTER</code></td>
            <td>Mendapatkan Kuartal pada Tanggal</td>
        </tr>
        <tr>
            <td><code>HOUR</code></td>
            <td>Mendapatkan Jam pada Waktu</td>
        </tr>
        <tr>
            <td><code>MINUTE</code></td>
            <td>Mendapatkan Menit pada Waktu</td>
        </tr>
        <tr>
            <td><code>SECOND</code></td>
            <td>Mendapatkan Detik pada Waktu</td>
        </tr>
    </tbody>
</table>
<br>

Namun jika menginginkan bagian yang lebih detail seperti Nama Bulan atau Nama Hari pada tanggal tertentu atau menampilkan format tanggal sesuai dengan keinginan dapat menggunakan sintaks `FORMAT_DATE(format_element, tanggal)`. <br><br>

<table border="1">
    <thead>
        <tr>
            <th>Sintaks</th>
            <th>Deskripsi</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><code>FORMAT_DATE('%A', tanggal)</code></td>
            <td>Mendapatkan Nama Hari pada Tanggal Tertentu</td>
        </tr>
        <tr>
            <td><code>FORMAT_DATE('%B', tanggal)</code></td>
            <td>Mendapatkan Nama Bulan pada Tanggal Tertentu</td>
        </tr>
    </tbody>
</table>
<br>

Detail format_element dapat diakses dilaman <a href="https://cloud.google.com/bigquery/docs/reference/standard-sql/format-elements#format_elements_date_time"> berikut</a>.

#### <i><b><span style='color:#55679C'>Quest</span> : Hitung total transaksi dan total pendapatan yang diperoleh tiap bulan pada tahun 2024 di DQPizza! </b></i><br>

In [ ]:
%%bigquery --project {project_id} --verbose

SELECT
  EXTRACT(YEAR FROM order_date) AS year,
  EXTRACT(MONTH FROM order_date) AS month,
  FORMAT_DATE('%B', order_date) AS month_name,
  COUNT(DISTINCT order_id) AS total_penjualan,
  SUM(price * quantity) AS total_pendapatan
FROM `dqlab-9876543.dq_pizza.f_detail_transaksi`
GROUP BY
  1,2,3
ORDER BY
  1,2

Executing query with job ID: 646e806a-5baa-49de-b31a-a59b1cf9a24c
Query executing: 0.59s
Job ID 646e806a-5baa-49de-b31a-a59b1cf9a24c successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

    year  month month_name  total_penjualan  total_pendapatan
0   2024      1    January             1845       565325730.0
1   2024      2   February             1685       527792760.0
2   2024      3      March             1840       570216510.0
3   2024      4      April             1795       556243605.0
4   2024      5        May             1853       578362275.0
5   2024      6       June             1773       552664620.0
6   2024      7       July             1935       587718990.0
7   2024      8     August             1841       553053825.0
8   2024      9  September             1661       520073055.0
9   2024     10    October             1646       518623560.0
10  2024     11   November             1792       570202335.0
11  2024     12   December             1680       524224710.0

# <b>D. <span style='color:#0B2F9F'><code>SUB-QUERY</code></span></b>
Subquery adalah sebuah query (pernyataan SQL) yang terletak di dalam query lain. Subquery dapat digunakan untuk mengambil data yang kemudian akan digunakan oleh query utama.<br><br>

#### <i><b><span style='color:#55679C'>Quest</span> : Pada tabel customers, hitung rata-rata umur customer dan bulatkan ke dua tempat desimal!</b></i>

In [ ]:
%%bigquery --project {project_id} --verbose

SELECT
  ROUND(AVG(DATE_DIFF(CURRENT_DATE(), PARSE_DATE('%Y-%m-%d',birth_date), YEAR)),2) AS age
FROM `dqlab-9876543.dq_pizza.customers`

Executing query with job ID: d9daefb4-471b-428b-964f-c5ce54ea11cb
Query executing: 0.60s
Job ID d9daefb4-471b-428b-964f-c5ce54ea11cb successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

     age
0  34.04

#### <i><b><span style='color:#55679C'>Quest</span> : Pada tabel customers, tampilkan customer_id, age dan gendernya dimana umur customer tersebut lebih dari rata-rata umur customer secara keseluruhan!</b></i>

In [ ]:
%%bigquery --project {project_id} --verbose

SELECT
  customer_id,
  DATE_DIFF(CURRENT_DATE(), PARSE_DATE('%Y-%m-%d',birth_date), YEAR) AS age,
  gender
FROM `dqlab-9876543.dq_pizza.customers`
WHERE
  DATE_DIFF(CURRENT_DATE(), PARSE_DATE('%Y-%m-%d',birth_date), YEAR)
  >
  (SELECT AVG(DATE_DIFF(CURRENT_DATE(), PARSE_DATE('%Y-%m-%d',birth_date), YEAR)) AS age FROM `dqlab-9876543.dq_pizza.customers`)

Executing query with job ID: 9d020049-a699-4a07-bc0f-456d286e7338
Query executing: 0.52s
Job ID 9d020049-a699-4a07-bc0f-456d286e7338 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

   customer_id  age gender
0   CUST007150   35      F
1   CUST007254   41      F
2   CUST004392   45      F
3   CUST004504   43      F
4   CUST001597   35      F
..         ...  ...    ...
64  CUST002244   45      M
65  CUST003103   37      M
66  CUST008804   37      M
67  CUST008854   38      M
68  CUST009522   36      M

[69 rows x 3 columns]

# <b>E. <span style='color:#0B2F9F'><code>Common Table Expression (CTE)</code></span></b>
CTE, atau Common Table Expression, adalah fitur dalam SQL yang memungkinkan Anda untuk mendefinisikan sebuah query sementara yang dapat digunakan dalam query lain. CTE membantu dalam membuat query lebih mudah dibaca dan dipelihara, serta memungkinkan penggunaan rekursi dalam query.

<img src="https://learnsql.com/blog/sql-common-table-expression-guide/cte_syntax_example.webp" width="50%">

#### <i><b><span style='color:#55679C'>Quest</span> : Siapakah customer yang paling banyak spending money di DQPizza?</b></i>

In [ ]:
%%bigquery --project {project_id} --verbose

WITH temp_table AS (
  SELECT
    order_id,
    customer_id,
    SUM(price * quantity) AS total_spending
  FROM `dqlab-9876543.dq_pizza.f_detail_transaksi`
  WHERE order_details_id IS NOT NULL
  GROUP BY order_id,customer_id
)
SELECT
  customer_id,
  total_spending
FROM temp_table
WHERE
  total_spending = (SELECT MAX(total_spending) FROM temp_table)

Executing query with job ID: f7b1dc1c-0fd8-4451-9cb8-11581af58bc1
Query executing: 0.88s
Job ID f7b1dc1c-0fd8-4451-9cb8-11581af58bc1 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

  customer_id  total_spending
0  CUST007150       3598020.0

Data Source : <i>https://mavenanalytics.io/challenges/maven-pizza-challenge</i> (dengan modifikasi)


---

<br>
<a href="https://www.linkedin.com/in/putri-hasinatuzzafira/"><img src="https://img.shields.io/badge/-© 2025 Putri Hasinatuzzafira-417DAC?style=for-the-badge&logoColor=white"/></a>

<a href="https://dqlab.id/"><img src="https://dqlab.id/files/dqlab/cache/87e30118ebba5ec7d96f6ea8c9dcc10b_x_118_X_55.png" align="left" /></a>