# <b><span style='color:#0B2F9F'>Pengantar</span></b>

Dalam pengelolaan data, sering kali informasi yang dibutuhkan tersebar di beberapa tabel yang saling berhubungan. Untuk memperoleh gambaran yang utuh, diperlukan cara untuk menggabungkan data-data tersebut secara tepat dan efisien. Konsep JOIN dalam SQL memungkinkan penggabungan data dari dua atau lebih tabel berdasarkan kolom yang memiliki relasi tertentu, sehingga informasi yang terpisah dapat ditampilkan dalam satu hasil query yang terpadu. Dengan memahami dan menerapkan berbagai jenis JOIN—seperti INNER JOIN, LEFT JOIN, RIGHT JOIN, dan FULL JOIN—seseorang dapat mengintegrasikan data dengan lebih fleksibel, memperkaya hasil analisis, serta meningkatkan ketepatan dalam pengambilan keputusan berbasis data.

# <b><span style='color:#0B2F9F'>Entity Relationalship Diagram</span></b>

Dalam sistem pemesanan pizza, terdapat beberapa entitas utama yang saling berhubungan. ERD (Entity Relationship Diagram) membantu menggambarkan hubungan antar tabel tersebut agar struktur data lebih mudah dipahami dan dikelola.

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/refs/heads/main/Image/Materi-SQL/ERD%20-%20Pizza.png" width="60%">

Antar tabel bisa saling berelasi sesuai dengan peran dan hubungan logisnya melalui sebuah 'kunci'

# <b><span style='color:#0B2F9F'>Set up</span></b>

Dibutuhkan proses autentikasi dari Google Colab ke Google Big Query. Ikuti langkah berikut https://drive.google.com/file/d/1gW8alZ_PrvcrsieqWCHOR4ssLI_25BRc/view untuk detail step-by-step nya

In [ ]:
# Import library yang dibutuhkan
from google.colab import auth, data_table
from google.cloud import bigquery
from pandas_gbq import to_gbq
import pandas as pd
pd.set_option('display.float_format', '{:.2f}'.format)

# Proses autentikasi akun
auth.authenticate_user()
print('Authenticated')

Authenticated

In [ ]:
# Buat BigQuery client
project_id = 'dqlab-putri512'
client = bigquery.Client(project = project_id)

# <b>A. <span style='color:#0B2F9F'><code>PREFIX</code></span></b>
Prefix merupakan penggunaan awalan pada nama tabel untuk memberikan informasi tambahan atau untuk mengelompokkan objek-objek tertentu. Sebagai contoh perhatikan gambar berikut : <br>

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/refs/heads/main/Image/Materi-SQL/SQL%20-%20Prefix.png" width="50%">

<br>

Nama tabel dimisalkan (diberi alias) sebagai tbl, lalu untuk mengakses kolom pada tabel tersebut bisa diberi prefix tbl.kolom1 dan seterusnya

#### <i><b><span style='color:#55679C'>Quest</span> : Pada tabel customers, ambil kolom customer_id, name dan gender namun gunakan alias 'c' pada nama tabel dan sematkan prefixnya saat mengakses kolom!</b></i>

In [ ]:
%%bigquery --project {project_id} --verbose

SELECT c.customer_id, c.customer_name, c.gender
FROM dqlab-9876543.dq_pizza.customers c

Executing query with job ID: 2b791df2-90cb-4d60-a516-4baab3d4e46f
Query executing: 0.48s
Job ID 2b791df2-90cb-4d60-a516-4baab3d4e46f successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

    customer_id           customer_name gender
0    CUST007150     Salsabila Purnawati      F
1    CUST003319      Cornelia Wijayanti      F
2    CUST007254            Elma Maryati      F
3    CUST004392            Najwa Natsir      F
4    CUST005127           Hani Palastri      F
..          ...                     ...    ...
132  CUST009056           Gada Winarsih      M
133  CUST009366        Mulyanto Suryono      M
134  CUST009522  Cakrawangsa Hutagalung      M
135  CUST009700       Asirwanda Hidayat      M
136  CUST009875            Wadi Jailani      M

[137 rows x 3 columns]

# <b>B. <span style='color:#0B2F9F'><code>JOIN</code></span></b>

Data biasanya disimpan di berbagai tabel atau sistem yang berbeda pada RDBMS (Relational Database Management System). JOIN memungkinkan pengguna untuk menggabungkan data dari berbagai sumber untuk mendapatkan gambaran yang lebih lengkap. Memahami query JOIN memungkinkan seorang pengguna untuk mengintegrasikan dan menganalisis data secara efektif, sehingga dapat meningkatkan kualitas analisis dan mendukung pengambilan keputusan berbasis data.

Operasi JOIN standar dapat dilakukan jika terdapat kunci pada tiap tabel yang saling terhubung. Operasi join dasar yang paling umum digunakan ada 4 yakni :
<ul>
    <li><b>LEFT JOIN</b></li>
    LEFT JOIN adalah jenis operasi penggabungan baris dari dua tabel, tetapi hanya mengembalikan semua baris dari tabel kiri (tabel pertama) dan baris yang cocok dari tabel kanan (tabel kedua). Jika tidak ada kecocokan di tabel kanan, maka nilai-nilai untuk kolom dari tabel kanan akan diisi dengan NULL.<br><br>
    <img src="https://thomasadventure.blog/img/left-join-extra.gif" width="20%">
    <br><br>
    <li><b>RIGHT JOIN</b></li>
    RIGHT JOIN adalah jenis operasi penggabungan baris dari dua tabel, tetapi hanya mengembalikan semua baris dari tabel kanan (tabel kedua) dan baris yang cocok dari tabel kiri (tabel pertama). Jika tidak ada kecocokan di tabel kiri, maka nilai-nilai untuk kolom dari tabel kiri akan diisi dengan NULL.<br><br>
    <img src="https://thomasadventure.blog/img/right-join.gif" width="20%">
    <br><br>
    <li><b>INNER JOIN</b></li>
    INNER JOIN adalah jenis operasi penggabungan yang hanya mengembalikan baris yang memiliki kecocokan di kedua tabel berdasarkan kriteria tertentu.<br><br>
    <img src="https://thomasadventure.blog/img/inner-join.gif" width="20%">
    <br><br>
     <li><b>FULL JOIN</b></li>
    FULL JOIN adalah jenis operasi penggabungan semua baris dari kedua tabel, baik yang memiliki kecocokan maupun yang tidak. Dengan demikian, hasilnya akan mencakup semua data dari tabel kiri dan tabel kanan.<br><br>
    <img src="https://thomasadventure.blog/img/full-join.gif" width="20%">
    <br><br>
</ul>

#### <i><b><span style='color:#55679C'>Quest : </span>Untuk mengetahui informasi mengenai banyak transaksi tiap customer (yang pernah bertransaksi saja); tampilkan customer_id, nama, gender, banyak transaksi yang pernah dilakukan urutkan berdasarkan transaksi terbanyak!

In [ ]:
%%bigquery --project {project_id} --verbose

SELECT
  c.customer_id,
  c.customer_name,
  c.gender,
  COUNT(o.order_id) AS banyak_transaksi
FROM dqlab-9876543.dq_pizza.customers c LEFT JOIN dqlab-9876543.dq_pizza.orders o on o.customer_id = c.customer_id
GROUP BY c.customer_id, c.customer_name, c.gender
HAVING COUNT(o.order_id) > 0
ORDER BY banyak_transaksi DESC

Executing query with job ID: 1b342e95-e6d9-4d08-b9e0-ded6cf8c24d6
Query executing: 0.60s
Job ID 1b342e95-e6d9-4d08-b9e0-ded6cf8c24d6 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

    customer_id       customer_name gender  banyak_transaksi
0    CUST006333  Darijan Nainggolan      M               741
1    CUST009381          Ani Habibi      F               702
2    CUST007656     Kusuma Prastuti      M               614
3    CUST003549      Laras Palastri      F               580
4    CUST009740       Mujur Jailani      M               523
..          ...                 ...    ...               ...
115  CUST002478       Alika Nugroho      F                17
116  CUST004307       Jelita Waluyo      F                17
117  CUST001029      Alika Dongoran      F                14
118  CUST003871     Paulin Najmudin      F                13
119  CUST006892     Emong Manullang      M                12

[120 rows x 4 columns]

#### <i><b><span style='color:#55679C'>Quest : </span>Kita perlu approch customer terdaftar namun belum pernah bertransaksi (belum pernah membeli pizza) di DQPizza, tampilkan identitas lengkap customer sesuai kriteria tersebut!

In [ ]:
%%bigquery --project {project_id} --verbose

SELECT
  c.*
FROM dqlab-9876543.dq_pizza.customers c LEFT JOIN dqlab-9876543.dq_pizza.orders o on o.customer_id = c.customer_id
WHERE o.order_id IS NULL

Executing query with job ID: edfd077f-3452-4d78-ad88-56d5cc3db6e6
Query executing: 0.69s
Job ID edfd077f-3452-4d78-ad88-56d5cc3db6e6 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,customer_id,customer_name,gender,birth_date,phone_number,email
0,CUST008842,Ani Purnawati,F,1998-12-13,+62 (0295) 880 4741,ani.purnawati@hotmail.com
1,CUST008966,Rahmi Padmasari,F,1980-11-06,+62 (027) 871 2336,rahmi.padmasari@gmail.com
2,CUST009022,Raisa Puspasari,F,1986-09-30,+62 (0743) 448 8286,raisa.puspasari@yahoo.com
3,CUST009070,Shania Tampubolon,F,2003-04-19,+62 (025) 592 9792,shania.tampubolon@gmail.com
4,CUST009403,Ifa Halimah,F,1983-12-24,+62 (91) 114-8861,ifa.halimah@hotmail.com
5,CUST009448,Cinthia Mayasari,F,1994-07-03,+62 (304) 769-4866,cinthia.mayasari@hotmail.com
6,CUST009620,Ratna Pradipta,F,1987-11-14,+62 (149) 212-4956,ratna.pradipta@yahoo.com
7,CUST009942,Jessica Wulandari,F,2005-08-29,080 239 5170,jessica.wulandari@yahoo.com
8,CUST009990,Rina Uyainah,F,1984-08-05,(0829) 610 9735,rina.uyainah@yahoo.com
9,CUST008804,Arsipatra Prabowo,M,1988-04-30,+62 (031) 219-5383,arsipatra.prabowo@gmail.com
10,CUST008854,Nrima Damanik,M,1987-03-19,+62 (503) 118-7949,nrima.damanik@yahoo.com
11,CUST008990,Rangga Nababan,M,2007-01-04,+62-0992-496-9678,rangga.nababan@gmail.com
12,CUST009056,Gada Winarsih,M,2000-12-07,0809259635,gada.winarsih@hotmail.com
13,CUST009366,Mulyanto Suryono,M,2001-02-17,+62-0885-877-0893,mulyanto.suryono@yahoo.com
14,CUST009522,Cakrawangsa Hutagalung,M,1989-03-25,+62 (39) 581-0404,cakrawangsa.hutagalung@gmail.com
15,CUST009700,Asirwanda Hidayat,M,1991-01-15,0837121476,asirwanda.hidayat@hotmail.com
16,CUST009875,Wadi Jailani,M,1996-02-28,088 915 7132,wadi.jailani@yahoo.com

#### <i><b><span style='color:#55679C'>Quest : </span>Kategori pizza apa yang menyumbang pendapatan paling besar di DQPizza pada tahun 2024?

In [ ]:
%%bigquery --project {project_id} --verbose

WITH temp_pizza AS (
  SELECT
    pizza_id,
    pizza_type_id,
    size,
    CAST(REPLACE(price,'IDR','') AS FLOAT64) AS price
   FROM dqlab-9876543.dq_pizza.pizzas
), temp_pizza_types AS (
  SELECT
    pizza_type_id,
    name,
    UPPER(category) AS category
  FROM dqlab-9876543.dq_pizza.pizza_types
)
SELECT
  pt.category,
  CONCAT('Rp', FORMAT("%'.0f", SUM(od.quantity * p.price) )) AS total_revenue
FROM dqlab-9876543.dq_pizza.order_details AS od
INNER JOIN temp_pizza AS p ON od.pizza_id = p.pizza_id
INNER JOIN temp_pizza_types AS pt ON p.pizza_type_id = pt.pizza_type_id
GROUP BY 1
ORDER BY 2 DESC

Executing query with job ID: 9942d716-73f9-4f6f-b14d-f943ebb380bc
Query executing: 0.57s
Job ID 9942d716-73f9-4f6f-b14d-f943ebb380bc successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

  category    total_revenue
0  CLASSIC  Rp1,782,644,760
1  SUPREME  Rp1,686,395,700
2  CHICKEN  Rp1,586,947,950
3   VEGGIE  Rp1,569,038,040

Data Source : <i>https://mavenanalytics.io/challenges/maven-pizza-challenge</i> (dengan modifikasi)


---

<br>
<a href="https://www.linkedin.com/in/putri-hasinatuzzafira/"><img src="https://img.shields.io/badge/-© 2025 Putri Hasinatuzzafira-417DAC?style=for-the-badge&logoColor=white"/></a>

<a href="https://dqlab.id/"><img src="https://dqlab.id/files/dqlab/cache/87e30118ebba5ec7d96f6ea8c9dcc10b_x_118_X_55.png" align="left" /></a>